const expertiseAreas = [
  "Desarrollo de software",
  "Seguridad informática",
  "Inteligencia artificial",
  "Redes y comunicaciones",
  "Bases de datos",
  "Ingeniería de software",
  "Sistemas distribuidos",
  "Computación en la nube",
  "Arquitectura de software",
  "Realidad virtual y aumentada",
  "Diseño de interfaces de usuario",
  "Análisis de datos",
  "Computación gráfica",
  "Criptografía",
  "Robótica",
  "Computación móvil",
  "Big Data",
  "Gestión de proyectos de TI",
  "Sistemas embebidos",
  "Computación cuántica",
  "Bioinformática",
  "Internet de las cosas (IoT)",
  "Ingeniería de rendimiento de software",
  "Experiencia de usuario (UX)",
  "Aprendizaje automático (Machine Learning)",
  "Minería de datos",
  "Programación concurrente",
  "Desarrollo web",
  "Optimización de sistemas",
  "Simulación y modelado",
  "Ingeniería de software orientada a objetos",
  "Realidad aumentada",
  "Ingeniería inversa",
  "Ingeniería del conocimiento",
  "Computación bioinspirada",
  "Computación en tiempo real",
  "Visión por computadora",
  "Computación evolutiva",
  "Redes neuronales artificiales",
  "Ingeniería de sistemas",
  "Ingeniería de datos",
  "Computación forense",
  "Automatización de procesos",
  "Desarrollo de videojuegos",
  "Interacción persona-computadora",
  "Ingeniería de calidad de software",
  "Computación cognitiva",
  "Programación de sistemas",
  "Ingeniería de ciberseguridad",
  "Desarrollo de aplicaciones móviles",
  "Gestión de la tecnología",
  "Ingeniería de redes",
  "Ingeniería de pruebas de software",
  "Ingeniería de sistemas embebidos",
  "Computación distribuida",
  "Computación paralela",
  "Ingeniería de software en tiempo real",
  "Ingeniería de requisitos",
  "Gestión de la información",
  "Realidad mixta",
  "Ingeniería de sistemas inteligentes",
  "Arquitectura empresarial",
  "Automatización de pruebas de software",
  "Ingeniería de usabilidad",
  "Ingeniería de sistemas de información",
  "Ingeniería de sistemas de tiempo real",
  "Ingeniería de sistemas de información geográfica",
  "Ingeniería de sistemas en la nube",
  "Ingeniería de sistemas orientada a servicios",
  "Ingeniería de sistemas colaborativos",
  "Ingeniería de sistemas de control",
  "Ingeniería de sistemas de producción",
  "Ingeniería de sistemas electrónicos",
  "Ingeniería de sistemas de transporte",
  "Ingeniería de sistemas de seguridad",
  "Ingeniería de sistemas de comunicación",
  "Ingeniería de sistemas de energía",
  "Ingeniería de sistemas de salud",
  "Ingeniería de sistemas de gestión",
  "Ingeniería de sistemas de calidad",
];

export default expertiseAreas;
