const expertiseAreas = [
  "Desarrollo de software",
  "Seguridad informática",
  "Inteligencia artificial",
  "Redes y comunicaciones",
  "Bases de datos",
  "Ingeniería de software",
  "Sistemas distribuidos",
  "Computación en la nube",
  "Arquitectura de software",
  "Realidad virtual y aumentada",
  "Diseño de interfaces de usuario",
  "Análisis de datos",
  "Computación gráfica",
  "Criptografía",
  "Robótica",
  "Computación móvil",
  "Big Data",
  "Gestión de proyectos de TI",
  "Sistemas embebidos",
  "Computación cuántica",
  "Bioinformática",
  "Internet de las cosas (IoT)",
  "Ingeniería de rendimiento de software",
  "Experiencia de usuario (UX)",
  "Aprendizaje automático (Machine Learning)",
  "Minería de datos",
  "Programación concurrente",
  "Desarrollo web",
  "Optimización de sistemas",
  "Simulación y modelado",
  "Ingeniería de software orientada a objetos",
  "Realidad aumentada",
  "Ingeniería inversa",
  "Ingeniería del conocimiento",
  "Computación bioinspirada",
  "Computación en tiempo real",
  "Visión por computadora",
  "Computación evolutiva",
  "Redes neuronales artificiales",
  "Ingeniería de sistemas",
  "Ingeniería de datos",
  "Computación forense",
  "Automatización de procesos",
  "Desarrollo de videojuegos",
  "Interacción persona-computadora",
  "Ingeniería de calidad de software",
  "Computación cognitiva",
  "Programación de sistemas",
  "Ingeniería de ciberseguridad",
  "Desarrollo de aplicaciones móviles",
  "Gestión de la tecnología",
  "Ingeniería de redes",
  "Ingeniería de pruebas de software",
  "Ingeniería de sistemas embebidos",
  "Computación distribuida",
  "Computación paralela",
  "Ingeniería de software en tiempo real",
  "Ingeniería de requisitos",
  "Gestión de la información",
  "Realidad mixta",
  "Ingeniería de sistemas inteligentes",
  "Arquitectura empresarial",
  "Automatización de pruebas de software",
  "Ingeniería de usabilidad",
  "Ingeniería de sistemas de información",
  "Ingeniería de sistemas de tiempo real",
  "Ingeniería de sistemas de información geográfica",
  "Ingeniería de sistemas en la nube",
  "Ingeniería de sistemas orientada a servicios",
  "Ingeniería de sistemas colaborativos",
  "Ingeniería de sistemas de control",
  "Ingeniería de sistemas de producción",
  "Ingeniería de sistemas electrónicos",
  "Ingeniería de sistemas de transporte",
  "Ingeniería de sistemas de seguridad",
  "Ingeniería de sistemas de comunicación",
  "Ingeniería de sistemas de energía",
  "Ingeniería de sistemas de salud",
  "Ingeniería de sistemas de gestión",
  "Ingeniería de sistemas de calidad",
  "Bases de datos",
  "Algoritmos",
  "Inteligencia artificial",
  "Desarrollo web",
  "Programación móvil",
  "Seguridad informática",
  "Análisis de datos",
  "Realidad virtual",
  "Computación en la nube",
  "Redes de computadoras",
  "Robótica",
  "Sistemas embebidos",
  "Arquitectura de software",
  "Visualización de datos",
  "Ingeniería del software",
  "Interacción persona-computadora",
  "Big data",
  "Computación gráfica",
  "Internet de las cosas (IoT)",
  "Aprendizaje automático (Machine Learning)",
  "Ingeniería de rendimiento de software",
  "Sistemas distribuidos",
  "Criptografía",
  "Ingeniería inversa",
  "Desarrollo de videojuegos",
  "Optimización de sistemas",
  "Simulación y modelado",
  "Ingeniería de calidad de software",
  "Computación cuántica",
  "Bioinformática",
  "Computación móvil",
  "Minería de datos",
  "Gestión de proyectos de TI",
  "Computación forense",
  "Ingeniería de sistemas inteligentes",
  "Ingeniería de sistemas de información",
  "Computación en tiempo real",
  "Diseño de interfaces de usuario",
  "Ingeniería de sistemas de comunicación",
  "Ingeniería de sistemas de seguridad",
  "Internet y tecnología de la información",
  "Ingeniería de sistemas de gestión",
  "Ingeniería de sistemas de energía",
  "Ingeniería de sistemas de transporte",
  "Ingeniería de sistemas de producción",
  "Ingeniería de sistemas de salud",
  "Ingeniería de sistemas de control",
  "Ingeniería de sistemas de tiempo real",
  "Ingeniería de sistemas de información geográfica",
  "Ingeniería de sistemas en la nube",
  "Ingeniería de sistemas orientada a servicios",
  "Ingeniería de sistemas colaborativos",
  "Ingeniería de sistemas electrónicos",
  "Ingeniería de sistemas de pruebas",
  "Ingeniería de sistemas de requisitos",
  "Ingeniería de sistemas de seguridad de la información",
  "Ingeniería de sistemas de gestión de bases de datos",
  "Ingeniería de sistemas de inteligencia de negocios",
  "Ingeniería de sistemas de análisis de datos",
  "Ingeniería de sistemas de optimización",
  "Ingeniería de sistemas de gestión de la información",
  "Ingeniería de sistemas de arquitectura empresarial",
  "Ingeniería de sistemas de desarrollo ágil",
  "Ingeniería de sistemas de gestión de proyectos",
  "Ingeniería de sistemas de integración de sistemas",
  "Ingeniería de sistemas de calidad de software",
  "Ingeniería de sistemas de diseño de software",
  "Ingeniería de sistemas de desarrollo de software",
  "Ingeniería de sistemas de mantenimiento de software",
  "Ingeniería de sistemas de seguridad de software",
  "Ingeniería de sistemas de pruebas de software",
  "Ingeniería de sistemas de gestión de configuración de software",
  "Ingeniería de sistemas de gestión de requisitos de software",
  "Ingeniería de sistemas de desarrollo web",
  "Ingeniería de sistemas de diseño de interfaces de usuario",
  "Ingeniería de sistemas de desarrollo de aplicaciones móviles",
  "Ingeniería de sistemas de análisis de seguridad",
  "Ingeniería de sistemas de auditoría de seguridad",
  "Ingeniería de sistemas de gestión de riesgos de seguridad",
  "Ingeniería de sistemas de criptografía y seguridad de la información",
  "Ingeniería de sistemas de protección de datos",
  "Ingeniería de sistemas de seguridad en redes",
  "Ingeniería de sistemas de administración de bases de datos",
  "Ingeniería de sistemas de diseño de bases de datos",
  "Ingeniería de sistemas de optimización de bases de datos",
  "Ingeniería de sistemas de minería de datos",
  "Ingeniería de sistemas de gestión de datos",
  "Ingeniería de sistemas de visualización de datos",
  "Ingeniería de sistemas de administración de proyectos",
  "Ingeniería de sistemas de liderazgo y gestión",
];

const uniqueExpertiseAreas = [...new Set(expertiseAreas)];

export default uniqueExpertiseAreas;
